---
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
  InstanceRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
         -
           Effect: Allow
           Action:
             - s3:Get*
             - s3:List*
             - autoscaling:Describe*
             - cloudformation:Describe*
             - cloudformation:GetTemplate
           Resource: "*"
      PolicyName: InstanceRole     # required
      Roles:                # optional, list of String
        - Ref: InstanceRole
  InstanceRoleInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: InstanceRole
