---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable HTTP access via port 80 and SSH access."
      VpcId:
        Fn::ImportValue: {'Fn::Sub': '${NetworkStackName}-VPCID'}
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
